trigger:
  - master

pool:
  vmImage: 'ubuntu-18.04'



steps:
  - script: |
      mvn install
    displayName: 'mvn install'
  - script: |
      sudo npm install -g snyk
      # create variable in Pipelines called 'SNYK_TOKEN' and securely save your Snyk token value
      # https://docs.microsoft.com/en-us/azure/devops/pipelines/process/variables
      sudo snyk auth $(SNYK_TOKEN) 
    displayName: 'install snyk'
  - script: |
      sudo snyk test
    displayName: 'sudo snyk test --fail-on=patchable'